version: "3.8"
services:
  postgres_db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: strapi-blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1A2b3c4229|
    ports:
      - "5432:5432" # Maps host port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists database data

volumes:
  postgres_data:
